  import type { Metadata } from "next"
  import { Inter } from "next/font/google"
  import "./globals.css"
  import StoreProvider from './StoreProvider'
  const inter = Inter({ subsets: ["latin"] })
  export const metadata: Metadata = {
    title: "Crework task app",
    description: "Generated by create next app",
  }

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode
  }>) {
    return (
      <html lang="en">
        <head>
        <link rel="icon" href="./favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Add other metadata here */}
      </head>
        <body className={inter.className}>
          <StoreProvider>
              {children}

          </StoreProvider>
        </body>
      </html>
    )
  }