version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env

  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env
